@url = http://localhost:3000
# @url = http://localhost:3000

# Create post

### POST /signing

POST {{url}}/signing
Content-Type: application/json

{
    "nom": "CHARLES",
    "prenom": "Emmanuel",
    "mail": "ccharlesemmanuel@gmail.com",
    "pseudo": "caf_dev", 
    "motDePasse": "charles25", 
    "short_description": "Passionné de JavaScript et de Node.js, j’apprends vite et vise le full stack… parce que pourquoi choisir entre front et back ?", 
    "photo": "photo_emmanuel.jpg" 
}

// mettre a jours les infos user

### PATCH /info/utilisateur/1
Content-Type: application/json

{
    
}

### POST /login

POST {{url}}/login
Content-Type: application/json

{
    "mail": "ccharlesemmanuel@gmail.com",
    "motDePasse": "charles25"
}

### POST /post/create

POST {{url}}/post/create
Content-Type: application/json

{
    "titre": "🚀 Je me lance dans l'apprentissage de Java EE !",
    "description": "Java EE (Enterprise Edition) est une plateforme pour créer des applis d'entreprise robustes avec des outils comme Servlets, JSP, EJB et JPA. Parfait pour gérer les transactions, la sécurité et les bases de données à grande échelle. #JavaEE #webdev #learning",
    "tags": "#new",
    "image": "java_ee.jpg",
    "lien": ""
}

### POST /projet/create

POST {{url}}/projet/create
Content-Type: application/json

  {
    "nom": "Projet Alpha",
    "description": "Description du projet Alpha",
    "tech": "JavaScript, Node.js",
    "defis": "Optimisation des performances, Scalabilité",
    "duree_realisation": "3 mois",
    "resultats": "Application fonctionnelle, Performance améliorée",
    "photo": "url_de_photo_alpha.jpg",
    "lien_demo": "https://lien-vers-la-demo-alpha.com",
    "lien_github": "https://github.com/utilisateur/projet-alpha"
  }

### DELETED /projet/:idProjet

DELETE {{url}}/projet/:idProjet
Content-Type: application/json

{
    "id": "<id_du_projet>"
}

### DELETED /post/:idPost

DELETE  {{url}/post/:idPost}
Content-Type: application/json

{
    "id": "id du post"
}




###POST

POST {{url}}/presentation/create
Content-Type: application/json

{
    "short_presentation": "Développeur web full stack avec une spécialisation en JavaScript et Node.js. Expérimenté en développement front et back-end','Développeur web full stack avec une spécialisation en JavaScript et Node.js.",
    "description": "Développeur web full stack avec une spécialisation en JavaScript et Node.js. Expérimenté en développement front et back-end','Développeur web full stack avec une spécialisation en JavaScript et Node.js. Expérimenté en développement front et back-end, avec des projets personnels et professionnels.", 
    "formation": "Bachelor en développement web", 
    "ecole": "IRIS School", 
    "photo": "presentationPhoto.png",
    "parcours": "Diplômé en tant que Développeur Web et Web Mobile (RNCP niveau 5), j’approfondis aujourd'hui mes compétences avec un Bachelor 3 en Développement Web. Passionné et déterminé à exceller dans le domaine !", 
    "ambitions": "Devenir expert en technologies JavaScript et contribuer à des projets innovants"
}

